import LegalLayout, { LegalSection } from '../../components/LegalLayout'

const CONTACT_EMAIL = 'hello@xeurotech.com'
const CONTACT_PHONE = '+92 303 8143000'

export default function Terms() {
  return (
    <LegalLayout
      eyebrow="Terms of Service"
      title="Terms & Conditions"
      intro="These Terms govern your use of AI Outfit Planner, a product of XeuroTech. By creating an account or using the App, you agree to these Terms."
      lastUpdated="August 2026"
    >
      <LegalSection title="1. Acceptance of these Terms">
        <p>
          By downloading, accessing, or using AI Outfit Planner (the "App"), you agree to be
          bound by these Terms of Service ("Terms"). If you don't agree, please don't use the
          App. XeuroTech may update these Terms from time to time; continued use after changes
          means you accept the updated Terms.
        </p>
      </LegalSection>

      <LegalSection title="2. About the service">
        <p>
          AI Outfit Planner helps you digitize your wardrobe and receive AI-generated outfit
          recommendations, chat with an AI stylist, plan outfits for future events, save your
          favorite looks, track wardrobe analytics, and (as a Premium feature) generate Virtual
          Try-On images of yourself in a given outfit. Features, availability, and pricing
          described on this website may change over time; we'll update this page when they do.
        </p>
      </LegalSection>

      <LegalSection title="3. Eligibility and accounts">
        <ul className="list-disc space-y-2 pl-5">
          <li>You must be at least 13 years old (or the minimum age of digital consent in your country) to create an account.</li>
          <li>You're responsible for maintaining the confidentiality of your account credentials and for all activity under your account.</li>
          <li>You agree to provide accurate information when creating your account and to keep it up to date.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Your content">
        <p>
          You retain ownership of the photos and content you upload (such as clothing photos and
          your profile picture) ("User Content"). By uploading User Content, you grant XeuroTech a
          limited, non-exclusive license to store, process, and display that content back to you
          within the App, and to send it to the third-party AI providers described in our Privacy
          Policy solely to provide the App's features (like generating outfit suggestions or a
          Virtual Try-On image). You confirm you have the right to upload the content you provide,
          and that it doesn't violate anyone else's rights.
        </p>
      </LegalSection>

      <LegalSection title="5. AI-generated content and accuracy">
        <p>
          Outfit recommendations, styling advice from the AI Stylist chat, match scores, and
          Virtual Try-On images are generated by AI models and are provided for informational and
          entertainment purposes. They are not professional styling, fashion, or medical advice,
          and may occasionally be inaccurate, unusual, or not reflect how an outfit will actually
          look or fit in real life. You're responsible for your own decisions about what to wear.
        </p>
      </LegalSection>

      <LegalSection title="6. Premium subscriptions and billing">
        <ul className="list-disc space-y-2 pl-5">
          <li>Premium is an optional, paid subscription (monthly or yearly) that unlocks additional features such as unlimited Virtual Try-On generations.</li>
          <li>Subscriptions are purchased, billed, and managed through Google Play Billing, and are subject to Google Play's payment terms.</li>
          <li>Subscriptions renew automatically at the end of each billing period unless cancelled beforehand through your Google Play account settings.</li>
          <li>Refunds are handled according to Google Play's refund policies; XeuroTech does not directly process payments or refunds.</li>
          <li>Pricing shown on this website may change at any time; the current price is always shown before you subscribe.</li>
        </ul>
      </LegalSection>

      <LegalSection title="7. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Use the App for any unlawful purpose or in violation of these Terms.</li>
          <li>Upload content that is illegal, infringing, or that you don't have the right to share.</li>
          <li>Attempt to reverse engineer, disrupt, or gain unauthorized access to the App or its underlying services.</li>
          <li>Use automated means (bots, scrapers) to access the App outside of its normal user interface.</li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Third-party services">
        <p>
          The App relies on third-party services to function, including Firebase (authentication
          and data storage), Cloudinary (image hosting), Google Gemini and OpenAI (AI outfit and
          image generation), Groq (AI chat), and Google Play Billing (subscriptions). Your use of
          the App is also subject to the applicable terms of these providers where relevant.
          XeuroTech is not responsible for outages or issues caused by these third-party services.
        </p>
      </LegalSection>

      <LegalSection title="9. Intellectual property">
        <p>
          The App, including its design, branding, logo, and underlying software (excluding your
          own User Content), is owned by XeuroTech and protected by applicable intellectual
          property laws. You may not copy, modify, or distribute any part of the App outside of
          normal, permitted use.
        </p>
      </LegalSection>

      <LegalSection title="10. Disclaimers">
        <p>
          The App is provided "as is" and "as available," without warranties of any kind, express
          or implied. XeuroTech does not guarantee that the App will be uninterrupted, error-free,
          or that AI-generated recommendations or images will meet your expectations.
        </p>
      </LegalSection>

      <LegalSection title="11. Limitation of liability">
        <p>
          To the fullest extent permitted by law, XeuroTech will not be liable for any indirect,
          incidental, or consequential damages arising from your use of the App, including
          reliance on AI-generated outfit suggestions or images. Our total liability for any claim
          related to the App is limited to the amount you paid us, if any, in the twelve months
          before the claim arose.
        </p>
      </LegalSection>

      <LegalSection title="12. Termination">
        <p>
          You may stop using the App and delete your account at any time. XeuroTech may suspend or
          terminate access to the App for violations of these Terms, misuse of the service, or as
          needed to protect other users or the platform.
        </p>
      </LegalSection>

      <LegalSection title="13. Changes to the service and these Terms">
        <p>
          Features, design, and pricing may change over time. We'll update these Terms as needed
          and note the "Last updated" date above. Material changes will be communicated within
          the App where practical.
        </p>
      </LegalSection>

      <LegalSection title="14. Governing law">
        <p>
          These Terms are governed by the laws of Pakistan, without regard to conflict-of-law
          principles, except where local consumer protection law in your country requires
          otherwise. Any dispute arising from these Terms or your use of the App will be subject
          to the exclusive jurisdiction of the courts of Pakistan.
        </p>
      </LegalSection>

      <LegalSection title="15. Contact us">
        <p>
          Questions about these Terms? Reach us at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="font-semibold text-ink underline decoration-violet/40 underline-offset-2 hover:text-violet">
            {CONTACT_EMAIL}
          </a>{' '}
          or{' '}
          <a href={`tel:${CONTACT_PHONE.replace(/[^+\d]/g, '')}`} className="font-semibold text-ink underline decoration-violet/40 underline-offset-2 hover:text-violet">
            {CONTACT_PHONE}
          </a>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
